// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarLeague.Data;

#nullable disable

namespace WarLeague.Data.Migrations
{
    [DbContext(typeof(WarLeagueDbContext))]
    partial class WarLeagueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarLeague.Data.Data.Entities.BanlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BanlistEntryCategory")
                        .HasColumnType("integer");

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("FormatId", "CardId")
                        .IsUnique();

                    b.ToTable("BanlistEntries");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Utf8Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YgoproId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("YgoproId")
                        .IsUnique();

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.PlayoffMatchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BracketPosition")
                        .HasColumnType("integer");

                    b.Property<string>("MatchupType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Team1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Team2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamWinnerId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.HasIndex("TeamWinnerId");

                    b.HasIndex("WeekId", "BracketPosition")
                        .IsUnique();

                    b.HasIndex("WeekId", "Team1Id", "Team2Id")
                        .IsUnique();

                    b.ToTable("PlayoffMatchups");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.RolePermissionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "PermissionType")
                        .IsUnique();

                    b.ToTable("RolePermissionMappings");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.RoundRobinMatchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MatchupType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Team1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Team2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamWinnerId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.HasIndex("TeamWinnerId");

                    b.HasIndex("WeekId", "Team1Id", "Team2Id")
                        .IsUnique();

                    b.ToTable("RoundRobinMatchups");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.TeamStandings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Tiebreaker")
                        .HasColumnType("integer");

                    b.Property<int?>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamStandings");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayoffTeamsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Name")
                        .IsUnique();

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.DeckSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeckFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.HasIndex("PlayerId", "WeekId")
                        .IsUnique();

                    b.ToTable("DeckSubmissions");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("LastLegalReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SingleFormatMode")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.HasIndex("GuildId", "SingleFormatMode")
                        .IsUnique()
                        .HasFilter("\"SingleFormatMode\" = TRUE");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MatchResultType")
                        .HasColumnType("text");

                    b.Property<int>("Player1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Player1Wins")
                        .HasColumnType("integer");

                    b.Property<int>("Player2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Player2Wins")
                        .HasColumnType("integer");

                    b.Property<string>("ReplayUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Team1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Team2Id")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.HasIndex("WinnerId");

                    b.HasIndex("WinnerTeamId");

                    b.HasIndex("WeekId", "Player1Id", "Player2Id")
                        .IsUnique();

                    b.ToTable("Matches", t =>
                        {
                            t.HasCheckConstraint("CK_Match_CanonicalOrder", "\"Player1Id\" < \"Player2Id\"");
                        });
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.PlayerSeasonTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("PlayerId", "SeasonId")
                        .IsUnique();

                    b.ToTable("PlayerSeasonTeams");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisableTeamModification")
                        .HasColumnType("boolean");

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumTeamMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId", "Active")
                        .IsUnique()
                        .HasFilter("\"Active\" = TRUE");

                    b.HasIndex("FormatId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaptainId")
                        .HasColumnType("integer");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DiscordRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("SeasonId", "CaptainId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "DiscordRoleId")
                        .IsUnique()
                        .HasFilter("\"DiscordRoleId\" IS NOT NULL");

                    b.HasIndex("SeasonId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmissionsClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubmissionsRequired")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Completed' AND \"Status\" <> 'NotOpenYet'");

                    b.HasIndex("SeasonId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.BanlistEntry", b =>
                {
                    b.HasOne("WarLeague.Data.Data.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Format", "Format")
                        .WithMany("BanlistEntries")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.PlayoffMatchup", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Team", "TeamWinner")
                        .WithMany()
                        .HasForeignKey("TeamWinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarLeague.Data.Entities.Week", "Week")
                        .WithMany("PlayoffMatchups")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team1");

                    b.Navigation("Team2");

                    b.Navigation("TeamWinner");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.RoundRobinMatchup", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Team", "TeamWinner")
                        .WithMany()
                        .HasForeignKey("TeamWinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarLeague.Data.Entities.Week", "Week")
                        .WithMany("RoundRobinMatchups")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team1");

                    b.Navigation("Team2");

                    b.Navigation("TeamWinner");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("WarLeague.Data.Data.Entities.TeamStandings", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Conference", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Season", "Season")
                        .WithMany("Conferences")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.DeckSubmission", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Player", "Player")
                        .WithMany("DeckSubmissions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Week", "Week")
                        .WithMany("DeckSubmissions")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Match", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Week", "Week")
                        .WithMany("Matches")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarLeague.Data.Entities.Team", "WinnerTeam")
                        .WithMany()
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Team1");

                    b.Navigation("Team2");

                    b.Navigation("Week");

                    b.Navigation("Winner");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.PlayerSeasonTeam", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Player", "Player")
                        .WithMany("PlayerSeasonTeams")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Season", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Format", "Format")
                        .WithMany("Seasons")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Format");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Team", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Player", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Conference", "Conference")
                        .WithMany("Teams")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarLeague.Data.Entities.Season", "Season")
                        .WithMany("Teams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("Conference");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Week", b =>
                {
                    b.HasOne("WarLeague.Data.Entities.Season", "Season")
                        .WithMany("Weeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Conference", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Format", b =>
                {
                    b.Navigation("BanlistEntries");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Player", b =>
                {
                    b.Navigation("DeckSubmissions");

                    b.Navigation("PlayerSeasonTeams");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Season", b =>
                {
                    b.Navigation("Conferences");

                    b.Navigation("Teams");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("WarLeague.Data.Entities.Week", b =>
                {
                    b.Navigation("DeckSubmissions");

                    b.Navigation("Matches");

                    b.Navigation("PlayoffMatchups");

                    b.Navigation("RoundRobinMatchups");
                });
#pragma warning restore 612, 618
        }
    }
}
